# Generated by Django 5.1.1 on 2024-10-03 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2024, 10, 3, 17, 33, 50, 931179, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
